---
layout: post
title:  "Java 6일차"
---




예외 처리
```java
/*
예외 (Exception)
정상적이지 않은 Case : 0으로 나누기, 배열의 인덱스 초과, 없는 파일 열기

finally : 예외 발생 여부와 관계없이 항상 실행되는 부분

throw : 예외를 발생 시킴
throws : 예외를 전가 시킴
 */
 
 
 
 // Java 프로그래밍 - 예외 처리

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;


class NotTenException extends RuntimeException {}

public class Main {

    public static boolean checkTen(int ten) {
        if (ten != 10) {
            return false;
        }

        return true;
    }

    public static boolean checkTenWithException(int ten) {

        try {
            if(ten != 10){
                throw new NotTenException();
            }
        } catch (NotTenException e) {
            System.out.println("e = " + e);
            return false;
        }

        return true;
    }

    public static boolean checkTenWithThrows(int ten) throws NotTenException {
        if(ten != 10){
            throw new NotTenException();
        }

        return true;
    } //함수를 호출한 쪽에서 예외 처리를 하면 된다.

    public static void main(String[] args) throws IOException {

//      1. 예외
//      1-1. 0으로 나누기
        System.out.println("== 0으로 나누기 ==");
//      int a = 5 / 0;

        try{
            int a = 5 / 0;
        } catch(ArithmeticException e) {
            System.out.println("0으로 나누기 예외 발생");
            System.out.println("e = " + e);
        } //결과 0으로 나누기 예외 발생
          //e = java.lang.ArithmeticException: / by zero
          //이렇게 하면 예외 발생으로 오류가 생기지 않고 뒤에 있는 코드들도 실행된다.
          //뒤에 finally { System.out.println("1-1 연습 종료"); } 이 코드를 넣으면
          // 1-1 연습 종료도 실행된다.

//      1-2. 배열 인덱스 초과
        System.out.println("== 배열 인덱스 초과 ==");
        int[] b = new int[4];
//        b[4] = 1;

        try {
            int a = 5 / 0;
        } catch(ArrayIndexOutOfBoundsException e) {
            System.out.println("e = " + e);
        }

//      1-3. 없는 파일 열기
        System.out.println("== 없는 파일 열기 ==");
//        BufferedReader br = new BufferedReader(new FileReader("abc.txt"));
//      try catch문을 이용하면 된다.


//      2. throw, throws
        System.out.println("== checkTen ==");
        boolean checkResult = Main.checkTen(10);
        System.out.println("checkResult = " + checkResult);


        System.out.println("== checkTenWithException ==");
        checkResult = Main.checkTenWithException(9);
        //10이 아닌 수가 입력되면 위에서 만든 NotTenException 예외가 발생한다.
        System.out.println("checkResult = " + checkResult);

        System.out.println("== checkTenWithThrows ==");

        try {
            checkResult = checkTenWithException(5);
        } catch (NotTenException e) {
            System.out.println("e = " + e);
        }
        System.out.println("checkResult = " + checkResult);
    }

}


```
